---
# Setup the zone forwarding for our lab - need to request things from production
- name: "Create the forward zone"
  redhat.rhel_idm.ipadnsforwardzone:
    ipaadmin_password: "{{ ipa_admin_password }}"
    state: present
    name: "{{ zone.name }}"
    forwarders: "{{ zone.forwarders }}"
    forwardpolicy: "{{ zone.forward_policy }}"
    skip_overlap_check: "{{ zone.skip_overlap_check }}"
