---
# Set up the prerequisites, install idm, configure idm
# our idm role encapsulates ipaserver and post configuration
- name: "Build the idm primary"
  hosts: idm_primary
  become: true
  gather_facts: true
  vars_files:
    - "~/rhisbuilder_vault.yml"

  tasks:

    - name: "Apply role idm_pre"
      ansible.builtin.include_role:
        name: idm_pre

    - name: "Apply role idm_primary"
      ansible.builtin.include_role:
        name: idm_primary

    # set the base configurations for the deployment
    - name: "Apply role idm_configuration"
      ansible.builtin.include_role:
        name: idm_config

    # ensure your id ranges before you create users
    # TODO - THIS ROLE DOES NOT EXIST
    # - name: "Apply role idm_id_ranges"
    #   ansible.builtin.include_role:
    #     name: idm_id_ranges

    # idp references must exist before you can
    # apply to a user authentication scheme
    - name: "Apply role idm_idp_reference"
      ansible.builtin.include_role:
        name: idm_idp_reference

    - name: "Apply role users"
      ansible.builtin.include_role:
        name: idm_users
        
    - name: "Apply role user_groups"
      ansible.builtin.include_role:
        name: idm_user_groups

    # password policy is applied to groups
    # group needs to exist of will policy creation/mod will fail
    - name: "Apply role idm_password_policy"
      ansible.builtin.include_role:
        name: idm_password_policy

    - name: "Apply role host_groups"
      ansible.builtin.include_role:
        name: idm_host_groups

    # Add the hosts do not support ipa_client
    # Add hosts that *do* support ipa_client
    - name: "Apply role hosts"
      ansible.builtin.include_role:
        name: idm_hosts

    - name: "Apply hbac policy"
      ansible.builtin.include_role:
        name: idm_hbac_policy

    - name: "Apply sudo policy"
      ansible.builtin.include_role:
        name: idm_sudo_policy

    # - name: "Apply dns setup"
    #   ansible.builtin.include_role:
    #     name: dns_setup
