---
# Set up the prerequisites, install idm, configure idm
# our idm role encapsulates ipaserver and post configuration
- name: "Register the provisioner to the idm primary"
  hosts: provisioner
  become: true
  gather_facts: true

  tasks:

    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Load the vault variables"
      when: vault_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vault_dir }}"

    - name: "Load the other variables"
      when: vars_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vars_dir }}"

    - name: "Apply role idm_client_register"
      ansible.builtin.include_role:
        name: idm_client_register
