---
- name: "Run Role"
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: "Load the vault variables"
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Apply role {{ role_name }}"
      ansible.builtin.include_role:
        name: "{{ role_name }}"
