---
- name: "Run Task"
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: "Load the vault variables"
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Run task - {{ task_name }}"
      ansible.builtin.include_tasks: tasks/{{ test_task_name }}.yml
