---

# standard topologies for rhis-builder-ipa'

idm_standard_topologies:
  - name: two_node
    size: 2
    segements:
      - direction: "left-to-right"
        left: 0
        right: 1
        state: "present"
        suffix: "domain+ca"
      - direction: "right-to-left"
        left: 0
        right: 1
        state: "present"
        suffix: "domain+ca"

  - name: three_node
    size: 3
    segements:
      - direction: "left-to-right"
        left: 0
        right: 1
        state: "present"
        suffix: "domain+ca"
      - direction: "right-to-left"
        left: 0
        right: 1
        state: "present"
        suffix: "domain+ca"
      - direction: "left-to-right"
        left: 1
        right: 2
        state: "present"
        suffix: "domain+ca"
      - direction: "right-to-left"
        left: 1
        right: 2
        state: "present"
        suffix: "domain+ca"
      - direction: "left-to-right"
        left: 2
        right: 0
        state: "present"
        suffix: "domain+ca"
      - direction: "right-to-left"
        left: 2
        right: 0
        state: "present"
        suffix: "domain+ca"

  - name: four_node
    size: 4
    segements:
      - direction: "left-to-right"
        left: 0
        right: 1
        state: "present"
        suffix: "domain+ca"
      - direction: "right-to-left"
        left: 0
        right: 1
        state: "present"
        suffix: "domain+ca"
      - direction: "left-to-right"
        left: 1
        right: 2
        state: "present"
        suffix: "domain+ca"
      - direction: "right-to-left"
        left: 1
        right: 2
        state: "present"
        suffix: "domain+ca"
      - direction: "left-to-right"
        left: 2
        right: 3
        state: "present"
        suffix: "domain+ca"
      - direction: "right-to-left"
        left: 2
        right: 3
        state: "present"
        suffix: "domain+ca"
      - direction: "left-to-right"
        left: 3
        right: 0
        state: "present"
        suffix: "domain+ca"
      - direction: "right-to-left"
        left: 3
        right: 0
        state: "present"
        suffix: "domain+ca"
