---

# Set these if you are forwarding zones (you probably are not)
idm_dns_forward_zones:
  - name: "parmstrong.ca"
    forwarders:
      - ip_address: "192.168.252.5"
      - ip_address: "192.168.252.6"
    forward_policy: "only"
    skip_overlap_check: true

# Set the bind policy for zones managed by the IdM server
idm_dns_update_zones:
  - name: "example.ca"
    foreman_proxy_BIND_update_policy: 'grant EXAMPLE.CA krb5-self * A; grant EXAMPLE.CA krb5-self * AAAA; grant EXAMPLE.CA krb5-self * SSHFP; grant realm-capsule\@EXAMPLE.CA wildcard * ANY;' # noqa yaml[line-length]
  - name: "168.192.in-addr.arpa"
    foreman_proxy_BIND_update_policy: 'grant EXAMPLE.CA krb5-subdomain 168.192.in-addr.arpa. PTR; grant realm-capsule\@EXAMPLE.CA wildcard * ANY;'
  - name: "140.168.192.in-addr.arpa"
    foreman_proxy_BIND_update_policy: 'grant EXAMPLE.CA krb5-subdomain 254.168.192.in-addr.arpa. PTR; grant realm-capsule\@EXAMPLE.CA wildcard * ANY;'
