---

# Sample of idm dns global configuration
# See the documentation for complete configuration details
# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/rhel_idm/content/module/ipadnsconfig/
#
# There is only ever one global configuration
#
# idm_dns_global_configuration:
#   forwarders: A list of fqdns of the servers to forward DNS queries to
#   forward_policy: One pf ['only', 'first', 'none'] to define how queries will be handled
#   action: 'dnsconfig' (d) or 'member' - only used with forwarders (e.g. with a forwarder list and state absent)
#   allow_sync_ptr: true or false - allow the synchronization of A and AAAA records with PTR records
#   state: 'present' (d) or 'absent'

# Manage the configuration for individual zones
# This is frequently used to update the bind policy to allow Satellite to configure DNS when provisioning
# See the documentation for complete configure parameters
# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/rhel_idm/content/module/ipadnszone/

idm_dns_zones:
  - name: "example.ca"
    update_policy: 'grant EXAMPLE.CA krb5-self * A; grant EXAMPLE.CA krb5-self * AAAA; grant EXAMPLE.CA krb5-self * SSHFP; grant realm-capsule\@EXAMPLE.CA wildcard * ANY;' # noqa yaml[line-length]
  - name: "168.192.in-addr.arpa"
    update_policy: 'grant EXAMPLE.CA krb5-subdomain 168.192.in-addr.arpa. PTR; grant realm-capsule\@EXAMPLE.CA wildcard * ANY;'
  - name: "140.168.192.in-addr.arpa"
    update_policy: 'grant EXAMPLE.CA krb5-subdomain 254.168.192.in-addr.arpa. PTR; grant realm-capsule\@EXAMPLE.CA wildcard * ANY;'


# Setting up a dns forward zone
# See the documentation for complete configuration details
# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/rhel_idm/content/module/ipadnsforwardzone/
#
# idm_dns_forward_zones:
#   - name: the zone being managed (the query zone to foreward)
#     action: 'dnsforwardzone' (d) or 'member' - work on the zone or a forwarding server
#     forwarders: A list of fqdns of the servers to forward DNS queries for this zone
#       - ip_address: ip of the forewarder (required)
#         port: port of the forewarder (NOT required) (d is None)
#     forward_policy: One pf ['only', 'first', 'none'] to define how queries will be handled in this zone
#     skip_overlap_check: 'true' or 'false'
#     permission: 'true' or 'false'  - system permission to manage the foreward zone
#     state: 'present' (d), 'absent', 'enabled', 'disabled'
#
# idm_dns_forward_zones:
#   - name: "parmstrong.ca"
#     forwarders:
#       - ip_address: "192.168.252.5"
#       - ip_address: "192.168.252.6"
#     forward_policy: "only"
#     skip_overlap_check: true
#     state: "present"
