---
# Use this section to configure user groups and users

idm_users:
  - login: "poc-admin"
    first: "POC"
    last: "Admin"
    city: "Waterloo"
    userstate: "Ontario"
    departmentnumber: "42"
    email: "poc_admin@example.ca"
    employnumber: "13"
    employeetype: "full-time"
    title: "POC Administrator"
  - login: "developer1"
    first: "Developer"
    last: "One"
    city: "Raliegh"
    userstate: "North Carolina"
    departmentnumber: "53"
    email: "developer1@example.ca"
    employnumber: "29"
    employeetype: "full-time"
    title: "Senior Developer"
  - login: "developer2"
    first: "Developer"
    last: "Two"
    city: "Ottawa"
    userstate: "Ontario"
    departmentnumber: "53"
    email: "developer2@example.ca"
    employnumber: "20"
    employeetype: "full-time"
    title: "Senior Developer"
  - login: "developer3"
    first: "Developer"
    last: "Three"
    city: "Montreal"
    userstate: "Quebec"
    departmentnumber: "53"
    email: "developer3@example.ca"
    employnumber: "1"
    employeetype: "full-time"
    title: "Principal Data Scientist"
  - login: "sat-admin"
    first: "Sat"
    last: "Admin"
  - login: "sat-org-admin"
    first: "Org"
    last: "Admin"
  - login: "site-admin"
    first: "Site"
    last: "Admin"
  - login: "comply-mgr"
    first: "Comply"
    last: "Mgr"
  - login: "comply-aud"
    first: "Comply"
    last: "Aud"
  - login: "pfy-operator"
    first: "PFY"
    last: "Operator"
  - login: "bofh"
    first: "B"
    last: "OperatorFH"
  - login: "content-mgr"
    first: "Content"
    last: "Mgr"

idm_user_groups:
  - name: "ug-services"
    description: "Service Accounts"
  - name: "ug-admins"
    description: "Environment Administrators"
    user_list:
      - "admin"
      - "poc-admin"
      - "bofh"
  - name: "ug-satellite-administrators"
    description: "Satellite Server Administrators"
    group_list:
      - ug-admins
    user_list:
      - "admin"
      - "poc-admin"
  - name: "ug-satellite-org-administrators"
    description: "Satellite Default Org Administrators - Manager Role for an Organization"
    user_list:
      - "sat-org-admin"
      - "poc-admin"
  - name: "ug-satellite-site-administrators"
    description: "Satellite Default Site Administrators - Manager Role for a Location"
    user_list:
      - "sat-org-admin"
      - "poc-admin"
  - name: "ug-satellite-compliance-managers"
    description: "Satellite Systems Compliance Managers - Full control compliance content"
    user_list:
      - "comply-mgr"
      - "poc-admin"
  - name: "ug-satellite-compliance-auditors"
    description: "Satellite Systems Compliance Auditors - Read only control compliance content"
    user_list:
      - "comply-aud"
      - "poc-admin"
  - name: "ug-satellite-operators"
    description: "Satellite Server Operators - Full control on hosts and content hosts"
    user_list:
      - "pfy-operator"
      - "bofh"
  - name: "ug-satellite-content-managers"
    description: "Satellite Content Managers - manage all content"
    user_list:
      - "content-mgr"
      - "poc-admin"
  - name: "ug-aap-administrators"
    description: "Ansible Automation Platform Administrators"
    group_list:
      - ug-admins
    user_list:
      - "poc-admin"
      - "bofh"
  - name: "ug-aap-auditors"
    description: "Ansible Automation Platform Auditors"
  - name: "ug-aap-operators"
    description: "Ansible Automation Platform Server Operators"
  - name: "ug-aap-project-managers"
    description: "Ansible Automation Platform Project Managers"
  - name: "ug-aap-template-managers"
    description: "Ansible Automation Platform Template Managers"
  - name: "ug-aap-users"
    description: "Ansible Automation Platform Users - can run basic Templates and Workflows"
    user_list:
      - "poc-admin"
      - "bofh"
      - "developer1"
      - "developer2"
      - "developer3"
  - name: "ug-aap-developers"
    description: "Ansible Automation Platform Programmers - an AAP power user"
    user_list:
      - "developer1"
      - "developer2"
      - "developer3"
  - name: "ug-prod-sysadmins"
    description: "Production System Administrators"
  - name: "ug-non-prod-sysadmins"
    description: "Non-production System Administrators"
  - name: "ug-web-server-administrators"
    description: "Web Server Administrators"
