---
#
# host resolves forward and backward OR
- name: "Make sure we are resolving internet addresses"
  ansible.builtin.assert:
    that: "{{ 'cdn.redhat.com' is ansible.utils.resolvable }}"

- name: "Make sure we are resolving internet addresses"
  ansible.builtin.assert:
    that: "{{ ansible_fqdn is ansible.utils.resolvable }}"

- name: "Configure /etc/hosts for resolve the local host if ipaserver_setup_dns is true"
  when: ipaserver_setup_dns is defined and ipaserver_setup_dns
  ansible.builtin.template:
    src: "etc_hosts.j2"
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: "0644"
