---

# ensure the (typically non-idmclient) hosts defined exist

- name: "Ensure the idm hosts configuration"
  when: idm_hosts is defined
  ansible.builtin.include_tasks: "ensure_host.yml"
  loop: "{{ idm_hosts }}"
  loop_control:
    loop_var: host
  no_log: true
  tags:
    - tags_rhisam
    - tags_idm_hosts
