---

# ensure the (typically non-idmclient) hosts defined exist

- name: "Configure the idm hosts specified for rh-isam sample environment"
  when: idm_hosts is defined
  ansible.builtin.include_tasks: "ensure_host.yml"
  loop: "{{ idm_hosts }}"
  loop_control:
    loop_var: idm_host
  no_log: true
  tags:
    - tags_rhisam
    - tags_idm_hosts
