---

# Ensure the DNS Forward Zone configuration

- name: "Ensure the DNS Forward Zone configuration - {{ idm_dns_forward_zone.name }}"
  redhat.rhel_idm.ipadnsforwardzone:
    ipaadmin_principal: "{{ ipa_admin_principal }}"                          # required
    ipaadmin_password: "{{ ipa_admin_password }}"                            # required
    name: "{{ idm_dns_forward_zone.name }}"                                  # required
    action: "{{ idm_dns_forward_zone.action | default(omit) }}"
    forward_policy: "{{ idm_dns_forward_zone.forward_policy | default(omit) }}"
    forwarders: "{{ idm_dns_forward_zone.forwarders | default(omit) }}"
    skip_overlap_check: "{{ idm_dns_forward_zone.skip_overlap_check | default(omit) }}"
    state: "{{ idm_dns_forward_zone.state | default(omit) }}"
