---
# Using single quotes as default requires doubles
# use the defaults from the global_policy so we don't get blank values


- name: "Ensure state for password policy for - {{ pwpolicy.group_name }}"
  redhat.rhel_idm.ipapwpolicy:
    ipaadmin_principal: '{{ ipa_admin_principal }}'
    ipaadmin_password: '{{ ipa_admin_password }}'
    name: '{{ pwpolicy.group_name }}'                           # must exist
    dictcheck: '{{ pwpolicy.dictcheck | default(omit) }}'       # default omit
    failinterval: '{{ pwpolicy.failinterval | default("60") }}' # 60 seconds
    gracelimit: '{{ pwpolicy.gracelimit | default("-1") }}'     # disabled
    history: '{{ pwpolicy.history | default("0") }}'            # no history kept
    lockouttime: '{{ pwpolicy.lockouttime | default("600") }}'  # 10 minutes in seconds
    maxfail: '{{ pwpolicy.maxfail | default("6") }}'            # 6 failures
    maxlife: '{{ pwpolicy.maxlife | default("90") }}'           # 90 days default
    maxrepeat: '{{ pwpolicy.maxrepeat | default(omit) }}'       # count - omitted
    maxsequence: '{{ pwpolicy.maxsequence | default(omit) }}'   # count - omitted
    minclasses: '{{ pwpolicy.minclasses | default("0") }}'      # no class count specified
    minlength: '{{ pwpolicy.minlength | default("8") }}'        # 8 characters min
    minlife: '{{ pwpolicy.minlife | default("1") }}'            # 1 hour between changes
    priority: '{{ pwpolicy.priority | default(omit) }}'         # int - must default to omit for global_policy
    usercheck: '{{ pwpolicy.usercheck | default(omit) }}'       # default omit
    state: '{{ pwpolicy.state | default("present") }}'
