---

# Variables that change the behaviour of rhis-builder-idm
# Turn off no_log: everywhere by setting this to true
# This will not work until 2.17 or later as
# "no_log: does not honour variable interpretation"
# https://github.com/ansible/ansible/issues/83323
# when this is fixed we will update the code to allow toggling
# no_log

main_logging: false
