---

- name: "Apply the segment"
  redhat.rhel_idm.ipatopologysegment:
    ipaadmin_principal: "{{ ipa_admin_principal }}"
    ipaadmin_password: "{{ ipa_admin_password }}"
    direction: "{{ current_tg_segment.direction }}"
    left: "{{ groups['idm_topology'][current_tg_segment.left] }}"
    right: "{{ groups['idm_topology'][current_tg_segment.right] }}"
    state: "{{ current_tg_segment.state }}"
    suffix: "{{ current_tg_segment.suffix }}"
